[package]
name = "hashing"
type = "lib"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v3.0.0-devnet.2", directory="noir-projects/aztec-nr/aztec" }
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "main", directory = "packages/merkle-trees" }
constants = { path = "../constants" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }